from pkg_resources import resource_filename
foo_config = resource_filename(__name__, 'foo.conf')

DICT_TXT_PATH = resource_filename(__name__, "data/dict/accents_dict.txt")
DICT_TRIE_PATH = resource_filename(__name__, "data/dict/accents_dict.trie")
CLASSIFIER_PATH = resource_filename(__name__, "data/classifier/")
MARKUP_XML_EXAMPLE = resource_filename(__name__, "data/examples/markup.xml")
MARKUP_JSON_EXAMPLE = resource_filename(__name__, "data/examples/markup.json")
TEXT_XML_EXAMPLE = resource_filename(__name__, "data/examples/text.xml")
TEXT_TXT_EXAMPLE = resource_filename(__name__, "data/examples/text.txt")
EXAMPLES_DIR = resource_filename(__name__, "data/examples/")
HYPHEN_TOKENS = resource_filename(__name__, "data/hyphen-tokens.txt")
G2P_RU_DICT_PATH = resource_filename(__name__, "data/dict/ru_g2p_dict.txt")
G2P_EN_DICT_PATH = resource_filename(__name__, "data/dict/en_g2p_dict.txt")
G2P_CLASSIFIER_DIR = resource_filename(__name__, "data/classifier/")
G2P_MODEL_PATH = resource_filename(__name__, "data/model.hdf5")
ACCENT_EN_DICT_PATH = resource_filename(__name__, "data/dict/en_accent_dict.txt")
G2P_DEFAULT_RU_MODEL = resource_filename(__name__, "data/g2p_models/RU_BLSTM256-DROP20-WER28-EPOCH10.hdf5")